inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/console
    - bin/rspec
    - bin/rubocop

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

Style/Documentation:
  Enabled: false
